# Generated by Django 4.0.6 on 2022-07-21 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_owner_pettreat_species_treat_pet_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='birth_date_lte',
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.datetime(2022, 7, 21, 10, 40, 41, 8635, tzinfo=utc))), name='birth_date_lte'),
        ),
    ]
