# Generated by Django 4.0.6 on 2022-07-21 10:47

import api.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pet_birth_date_lte_alter_pet_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='birth_date_lte',
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, validators=[api.models.validate_pretty_name]),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.datetime(2022, 7, 21, 10, 47, 16, 699540, tzinfo=utc))), name='birth_date_lte'),
        ),
    ]
