# Generated by Django 4.0.6 on 2022-07-22 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pet_birth_date_lte_alter_pet_owner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='birth_date_lte',
        ),
        migrations.RenameField(
            model_name='pettreat',
            old_name='pet_id',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='pettreat',
            old_name='treat_id',
            new_name='treat',
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.datetime(2022, 7, 22, 11, 3, 38, 468020, tzinfo=utc))), name='birth_date_lte'),
        ),
    ]
