# Generated by Django 4.0.6 on 2022-07-28 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_pet_birth_date_lte_pet_birth_date_lte'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pet',
            name='birth_date_lte',
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(check=models.Q(('birth_date__lte', datetime.datetime(2022, 7, 28, 12, 22, 56, 773796, tzinfo=utc))), name='birth_date_lte'),
        ),
    ]
